# Generated by Django 2.1.4 on 2018-12-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalType',
            fields=[
                ('biological_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('biological_type_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'biological type',
                'verbose_name_plural': 'biological types',
                'db_table': 'biological_type',
                'ordering': ['biological_type_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterAliase',
            fields=[
                ('character_aliase_id', models.AutoField(primary_key=True, serialize=False)),
                ('aliase', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'character aliase',
                'verbose_name_plural': 'character aliases',
                'db_table': 'character_aliase',
                'ordering': ['character', 'aliase'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterFamilyTie',
            fields=[
                ('family_tie_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'character family tie',
                'verbose_name_plural': 'character family ties',
                'db_table': 'character_family_tie',
                'ordering': ['character1', 'character2'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterInfo',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('is_male', models.IntegerField()),
                ('is_main_character', models.IntegerField()),
                ('brief_intro', models.TextField(blank=True, null=True)),
                ('full_intro', models.TextField()),
                ('character_url', models.CharField(max_length=255, unique=True)),
                ('character_img_file_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
                'db_table': 'character_info',
                'ordering': ['full_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterTitle',
            fields=[
                ('character_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'character title',
                'verbose_name_plural': 'character titles',
                'db_table': 'character_title',
                'ordering': ['character', 'title_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('culture_id', models.AutoField(primary_key=True, serialize=False)),
                ('culture_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'culture',
                'verbose_name_plural': 'cultures',
                'db_table': 'culture',
                'ordering': ['culture_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_name', models.CharField(max_length=100, unique=True)),
                ('season_num', models.IntegerField()),
                ('episode_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'episodes',
                'db_table': 'episode',
                'ordering': ['season_num', 'episode_num'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=100, unique=True)),
                ('house_img_file_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'db_table': 'house',
                'ordering': ['house_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('relation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'relation type',
                'verbose_name_plural': 'relation types',
                'db_table': 'relation_type',
                'ordering': ['relation_type_name'],
                'managed': False,
            },
        ),
    ]
